# cellchat - the host-to-plugin drawing protocol, in R.
#
# GENERATED by `scprofile scaffold cellchat`. Do not edit it here; edit the template in
# scprofile/scaffold.py and regenerate, or the next scaffold silently reverts you. `sch dev
# convert placement` regenerates this file and refuses a plugin whose copy has drifted.
#
# HOW A PLUGIN USES IT. Prepend it to every embedded R script the plugin runs, so ONE definition
# serves all of them:
#
#     script = _R_DRAW + _R_BODY            # in the Python that launches Rscript
#
# and configure it once per script, after `figdir` is known:
#
#     .figures(prefix = "native_", what = "native plot", w = 1800, h = 1500,
#              context = ctx_file, visible = function(id) draw_figs || id %in% profile_plots)
#
# WHY THIS IS ONE FILE AND NOT A BLOCK IN EACH SCRIPT. It was three blocks in one plugin, and the
# copies drifted. One of them recorded the cost in its own comment: a script "was written with only
# `npng` and then called `ndev` for the interaction heatmaps - could not find function ndev halted
# the whole framing loop after the first framing's scatter plots, so one framing of two was drawn
# and neither heatmap was. The sibling script had both wrappers; this one had one." A generated
# definition cannot have that defect. Three hand-written ones cannot avoid it.
#
# WHAT IS DELIBERATELY NOT HERE: anything about the method. This file knows about ceilings,
# captions, colours, devices and a phase clock - the things the HOST and the plugin agree on. It
# names no plotting function and no biology - except in THE PLAN at the end of it, which is
# generated from the plugin's own `report.figures`: one entry per figure family, and `.draw(id)`
# where a hand-written draw site used to stand. A figure is adjusted in the plan and regenerated;
# it is never edited here.

.figcfg <- new.env(parent = emptyenv())
.figcfg$prefix <- ""
.figcfg$what <- "figure"
.figcfg$w <- 1800
.figcfg$h <- 1400
.figcfg$res <- 200
.figcfg$visible <- function(id) TRUE

# WHAT THE HOST COMPUTED AND THE PLUGIN APPLIES. The host writes one tab-separated file beside the
# run and every row of it is a term of this contract: the provenance stamp, the sentence that says
# what an absent population means, the colour map that keeps one population one colour across every
# panel of the whole report, and the ceilings.
.fctx <- list(stamp = "", absence = "", colours = character(0), axis = "")
.ceil <- integer(0)

.plots <- new.env(); .plots$ok <- 0L; .plots$bad <- character(0)
.caps <- new.env(); .caps$rows <- list()
.ndrawn <- new.env(parent = emptyenv())

.figures <- function(prefix = "", what = "figure", w = 1800, h = 1400, res = 200,
                     context = "", visible = NULL) {
  .figcfg$prefix <- prefix
  .figcfg$what <- what
  .figcfg$w <- w
  .figcfg$h <- h
  .figcfg$res <- res
  if (!is.null(visible)) .figcfg$visible <- visible
  if (nzchar(context) && file.exists(context)) {
    fc <- tryCatch(utils::read.delim(context, header = FALSE, sep = "\t", quote = "",
                                     comment.char = "", stringsAsFactors = FALSE,
                                     col.names = c("k", "v")), error = function(e) NULL)
    if (!is.null(fc) && nrow(fc)) {
      .fctx$stamp <<- paste(fc$v[fc$k == "stamp"], collapse = "")
      .fctx$absence <<- paste(fc$v[fc$k == "absence"], collapse = "")
      .fctx$axis <<- paste(fc$v[fc$k == "axis"], collapse = "")
      cr <- fc[startsWith(fc$k, "colour:"), , drop = FALSE]
      if (nrow(cr)) .fctx$colours <<- stats::setNames(cr$v, sub("^colour:", "", cr$k))
      cl <- fc[startsWith(fc$k, "ceiling:"), , drop = FALSE]
      if (nrow(cl)) .ceil <<- stats::setNames(suppressWarnings(as.integer(cl$v)),
                                              sub("^ceiling:", "", cl$k))
    }
  }
  invisible(NULL)
}

# THE VECTOR A PLOTTING FUNCTION WANTS: IN THE OBJECT'S LEVEL ORDER, AND NAMED.
#
# Ordered, because a plotting function takes a colour vector POSITIONALLY against the object's
# factor levels and any other order colours the wrong populations. NAMED, because some upstream
# functions refuse an unnamed one outright while others accept it either way - so the vector
# satisfies the stricter of them. Dropping the names once cost 36 circle plots across 18 units in
# one run, and the per-unit tallies reported the failure while the run-level count said nothing.
#
# Returns NULL when the host gave no map or when any level is unmapped, because a partial vector is
# worse than none: the plotting function would recycle it silently.
.cols_for <- function(levs) {
  if (!length(.fctx$colours)) return(NULL)
  levs <- as.character(levs)
  if (!all(levs %in% names(.fctx$colours))) return(NULL)
  out <- .fctx$colours[levs]
  names(out) <- levs
  out
}

# A PHASE CLOCK, DEFINED AT THE TOP BECAUSE R DOES NOT HOIST. Twice the cost of a round has been
# diagnosed by assumption and been wrong: the inference was assumed dominant and was not, then the
# matrix write was, and it takes one to five seconds. Guessing where a run spends its time is what
# makes every round of development expensive, so the run measures itself.
#
# t0 IS ZERO, NOT "NOW". `proc.time()` elapsed is measured from the moment R STARTED, so anchoring
# the clock at zero makes the first mark cover everything before it - interpreter start-up and
# loading the wrapped tool and its dependencies. Anchored at "now" the first phase reported 0 while
# the cost it was supposed to name sat outside the clock entirely, and a line that says zero is
# worse than no line because it reads as a measurement.
.clock <- new.env(); .clock$t0 <- 0; .clock$marks <- list()
mark <- function(what) {
  now <- proc.time()[["elapsed"]]
  .clock$marks[[what]] <- now - .clock$t0
  .clock$t0 <- now
  invisible(NULL)
}

.legend <- function(fname, text, by) {
  if (!nzchar(text)) return(invisible(NULL))
  .caps$rows[[length(.caps$rows) + 1L]] <-
    # ONE LINE, ALWAYS. The file is tab-separated and written with quote = FALSE, so a caption
    # carrying a tab or a newline does not corrupt one row - it shifts every column after it, or
    # splits the row in two, and the reader then drops what it cannot parse WITHOUT SAYING SO.
    # Collapsing whitespace here matches what the reader does anyway and makes the written file
    # unable to express the broken shape.
    list(file = fname, caption = gsub("[[:space:]]+", " ", trimws(text)), drawn_by = by)
  invisible(NULL)
}

.write_captions <- function() {
  # CALLED ON EXIT AS WELL AS AT THE END. An abort in a later section left `captions.tsv`
  # unwritten, so panels drawn BEFORE the failure silently lost their legends and fell back to
  # their filenames - a degradation that renders as a normal page.
  if (!length(.caps$rows)) return(invisible(NULL))
  # ONCE PER SET OF ROWS. This is called explicitly at the end of a script AND by the finalizer
  # below, and writing the same file twice put a duplicate line in every run's log.
  if (identical(.caps$written, length(.caps$rows))) return(invisible(NULL))
  .caps$written <- length(.caps$rows)
  d <- do.call(rbind, lapply(.caps$rows, function(r) as.data.frame(r, stringsAsFactors = FALSE)))
  utils::write.table(d, file.path(figdir, "captions.tsv"),
                     sep = "\t", row.names = FALSE, quote = FALSE)
  cat("wrote", nrow(d), "figure legend(s)\n")
}

# WHEN THE SCRIPT ENDS, HOWEVER IT ENDS - AND `on.exit` IS NOT THAT. An abort in a later section
# left `captions.tsv` unwritten, so panels drawn BEFORE the failure silently lost their legends
# and fell back to their filenames, which renders as a perfectly normal page. The guard written
# against it was `on.exit(.write_captions(), add = TRUE)` at the top level of the script, and a
# top-level `on.exit` in `Rscript` NEVER RUNS - not on error and not on a clean exit. Measured
# both ways. A finalizer registered with `onexit = TRUE` runs in both cases, so the protection
# the comment described exists for the first time.
invisible(reg.finalizer(.caps, function(e) .write_captions(), onexit = TRUE))

# THE CEILING, ENFORCED BEFORE THE PLOT IS COMPUTED. R is lazy - `expr` is a promise until it is
# forced - so refusing here costs the call and nothing else. Longest prefix wins, as everywhere
# else a plugin states a rule and an exception together, and a family no ceiling covers is
# unbounded exactly as it was before this existed.
#
# WHY IT IS HERE AND NOT IN THE LOOPS. The bounds a plugin honoured were `head(paths, 6)` and
# `head(.ranked, 8)`, typed in by hand beside a declaration that said 12 and 8. The plan read the
# declaration, the run obeyed the literals, and they agreed only while somebody kept them in step.
# The number now exists once, in the declaration, and arrives here.
#
# A CEILING THE DRAWING CODE DOES NOT READ IS A COMMENT. Remove this guard and the plugin still
# declares its ceilings, still reports them, and draws without bound. That state was reached once
# and every build check reported the plugin finished; `sch dev convert placement` now asks.
.at_ceiling <- function(id) {
  if (!length(.ceil)) return(FALSE)
  k <- names(.ceil)[startsWith(id, names(.ceil))]
  if (!length(k)) return(FALSE)
  k <- k[which.max(nchar(k))]
  cap <- .ceil[[k]]
  if (is.na(cap)) return(FALSE)
  n <- if (is.null(.ndrawn[[k]])) 0L else .ndrawn[[k]]
  if (n >= cap) {
    cat("ceiling: ", id, " not drawn - ", k, " declares at most ", cap, " here\n", sep = "")
    return(TRUE)
  }
  .ndrawn[[k]] <- n + 1L
  FALSE
}

# THE ONE DEVICE PATH. `force_it` is the only thing the two public wrappers disagree about, and it
# is the difference between a function that RETURNS a plot object and one that DRAWS as a side
# effect - see `ndev` below.
#
# THE LEGEND SLOT IS THE PARAMETER WHOSE DEFAULT IS THE EMPTY STRING. That is how the maker finds
# it without being told a name, in R or in Python, so keep the default as it is.
.draw_one <- function(id, expr, force_it, w = .figcfg$w, h = .figcfg$h,
                      res = .figcfg$res, legend = "", by = "tool") {
  if (!isTRUE(.figcfg$visible(id))) return(invisible(NULL))
  full <- paste0(.figcfg$prefix, id)
  if (.at_ceiling(full)) return(invisible(NULL))
  path <- file.path(figdir, paste0(full, ".png"))
  .legend(basename(path), legend, by)
  ok <- tryCatch({
    grDevices::png(path, width = w, height = h, res = res)
    dn <- grDevices::dev.cur()
    # THE SAFETY NET NAMES ITS OWN DEVICE. An unqualified `dev.off()` here closes whatever is
    # current, which after the explicit close below is somebody else's device.
    on.exit(if (dn %in% grDevices::dev.list()) grDevices::dev.off(dn), add = TRUE)
    if (force_it) force(expr) else print(expr)
    # CLOSED BEFORE THE FILE IS ASKED ABOUT, and this is not tidiness. `on.exit` fires when the
    # FUNCTION returns, so with the close left to it the `file.exists` below runs while the
    # device is still open - and whether the file is there by then is a property of the platform:
    # the Linux png device creates it on open, the macOS one on close. Measured, on a wrapper
    # written exactly that way: every panel drawn correctly was counted as FAILED on macOS and as
    # written on the cluster, from one line of R.
    grDevices::dev.off(dn)
    TRUE
  }, error = function(e) {
    cat(.figcfg$what, id, "FAILED:", conditionMessage(e), "\n")
    FALSE
  })
  # THE FILE, NOT ONLY THE ABSENCE OF AN ERROR. A plotting call that returns quietly without
  # putting anything on the device leaves a path that does not exist, and counting that as drawn
  # is how a declared plot came to be promised and never produced.
  if (ok && file.exists(path)) {
    .plots$ok <- .plots$ok + 1L
    cat(.figcfg$what, id, "written\n")
  } else {
    .plots$bad <- c(.plots$bad, id)
    if (file.exists(path)) unlink(path)
  }
  invisible(NULL)
}

npng <- function(id, expr, w = .figcfg$w, h = .figcfg$h, res = .figcfg$res,
                 legend = "", by = "tool") {
  .draw_one(id, expr, FALSE, w, h, res, legend, by)
}

# Some functions DRAW rather than return - a base-graphics network, a grid object that must be
# drawn, a function whose value is NULL. `print` on those prints nothing or errors, so this second
# wrapper evaluates for the side effect instead.
ndev <- function(id, expr, w = .figcfg$w, h = .figcfg$h, res = .figcfg$res,
                 legend = "", by = "tool") {
  .draw_one(id, expr, TRUE, w, h, res, legend, by)
}

# ================================================================================================
# THE PLAN. GENERATED from `report.figures`; one entry per figure family this companion
# draws. Adjust the entry in the plugin's declaration and regenerate.
# ================================================================================================
.plan <- list()
.plan[["nativecmp_rankNet_stacked"]] <- list(
  id = "nativecmp_rankNet_stacked",
  axis = "contrast",
  by = "tool",
  fn = "rankNet",
  device = "png",
  at_most = 1,
  w = quote(1600),
  h = quote(2000),
  expr = quote({
 gg <- rankNet(m, mode = "comparison", stacked = TRUE, do.stat = TRUE, paired.test = FALSE)
 gg + ggplot2::labs(caption = paste0(
 "Pathway-name colour marks a SIGNIFICANT SHIFT toward that arm (rankNet's own paired test on relative flow), not exclusivity -\n",
 "a name can be coloured like one arm's bar while the bar still shows a segment for the other; only a bar with NO segment is exclusive.")) +
 ggplot2::theme(plot.caption = ggplot2::element_text(size = 7))
 }),
  legend = "Every pathway ranked by its relative information flow, each bar split between the two arms. Because the bars are normalised, this shows how a pathway's flow is divided between the arms and not how much flow it carries: a rare pathway and a dominant one can look identical here; the unstacked panel beside it carries the amounts. Pathway-name colour marks a significant shift toward one arm on a paired test of relative flow between the two arms, not exclusivity to that arm: a name can be coloured like one arm's bar while the bar still carries a visible segment for the other. Only a bar with no segment at all for the untested arm is actually exclusive to the coloured one.")
.plan[["nativecmp_interaction_flow"]] <- list(
  id = "nativecmp_interaction_flow",
  axis = "interaction",
  by = "plugin",
  fn = "",
  device = "png",
  at_most = 2,
  file = quote(paste0("interaction_flow__", safe)),
  expr = quote({ ggplot2::ggplot(both, ggplot2::aes(x = d2, y = d1)) + ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed", colour = "grey40") + ggplot2::geom_hline(yintercept = 0, colour = "grey85") + ggplot2::geom_vline(xintercept = 0, colour = "grey85") + ggplot2::geom_point(ggplot2::aes(colour = interaction), size = 2.4) + ggrepel::geom_text_repel(data = top, ggplot2::aes(label = name), size = 3, max.overlaps = 20, min.segment.length = 0) + ggplot2::scale_colour_gradient2(low = "#2166ac", mid = "grey90", high = "#b2182b", midpoint = 0, limits = c(-max(abs(both$interaction), na.rm = TRUE), max(abs(both$interaction), na.rm = TRUE))) + ggplot2::coord_equal(xlim = c(-lim, lim), ylim = c(-lim, lim)) + ggplot2::labs(x = paste0(eff_lbl, " within ", st[2], " (the control)"), y = paste0(eff_lbl, " within ", st[1]), colour = paste0("larger in\n", st[1], " (+) /\n", st[2], " (-)"), title = paste0("Does the ", fac, " response depend on ", as.character(rows$stratum_factor[1]), "?"), subtitle = paste0("ABOVE the dashed line: larger response in ", st[1], "   BELOW: larger in ", st[2], " (control)")) + ggplot2::theme_classic() }),
  legend = "Does the {fac} response depend on {as.character(rows$stratum_factor[1])}? One point per signalling pathway. The vertical axis is the {eff_lbl} within {st[1]}; the horizontal axis is the same response within {st[2]}, which is the control. The dashed line is no interaction, an identical response in both strata, so a point's distance from it is the interaction, and points above the line respond more in {st[1]}. Every value is a per-pathway contribution from the same ranked-flow test used elsewhere in this comparison; no test exists for a difference of two differences and none is claimed. Up to the twelve largest interactions are named, spaced apart rather than picked by size alone, so a labelled pathway can sit below one that is not if the larger one landed too close to a point already chosen. Every pathway's value is in the source table regardless of whether its name is drawn.")
.plan[["nativecmp_interaction_flow_log"]] <- list(
  id = "nativecmp_interaction_flow_log",
  axis = "interaction",
  by = "plugin",
  fn = "",
  device = "png",
  at_most = 2,
  w = quote(2000),
  h = quote(1900),
  when = quote(nrow(pos) >= 3),
  file = quote(paste0("interaction_flow_log__", safe)),
  expr = quote({ ggplot2::ggplot(pos, ggplot2::aes(x = l2, y = l1)) + ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed", colour = "grey40") + ggplot2::geom_point(ggplot2::aes(colour = li), size = 2.4) + ggrepel::geom_text_repel(data = ptop, ggplot2::aes(label = name), size = 3, max.overlaps = 20, min.segment.length = 0) + ggplot2::scale_colour_gradient2(low = "#2166ac", mid = "grey90", high = "#b2182b", midpoint = 0) + ggplot2::coord_equal(xlim = c(-lim2, lim2), ylim = c(-lim2, lim2)) + ggplot2::labs(x = paste0("log2 fold ", eff_lbl, " within ", st[2], " (the control)"), y = paste0("log2 fold ", eff_lbl, " within ", st[1]), colour = paste0("larger in\n", st[1], " (+) /\n", st[2], " (-)"), title = paste0("Does the ", fac, " response depend on ", as.character(rows$stratum_factor[1]), "? - multiplicative scale"), subtitle = paste0(nrow(pos), " of ", nrow(both), " pathways; the rest ", "are absent from an arm and have no fold change; axes span the largest log2 fold change actually plotted, so one extreme pathway widens the margin for every other point")) + ggplot2::theme_classic() }),
  legend = "The same question on the multiplicative scale: log2 fold {eff_lbl} within {st[1]} against the same within {st[2]}, the control. Here no interaction means the same fold change in both strata rather than the same absolute change, which is a different question and can rank pathways differently. Drawn only on the {nrow(pos)} of {nrow(both)} pathways present in all four arms; the rest are absent from one arm and have no fold change, which is why this panel never appears without the additive one beside it. The axes are cropped to the data the same way the additive panel's are, to the largest log2 value actually plotted on either axis, but a log-ratio has a far longer tail than a bounded probability difference, so one pathway near a zero denominator can widen the shared range well past where most points sit; that margin is a real value on the plate, not unused space, and tightening it would mean clipping that pathway out of view. The on-plot subtitle is cut by the canvas edge on some renders, ending mid-sentence after so one ex; the sentence it was completing in full is: axes span the largest log2 fold change actually plotted, so one extreme pathway widens the margin for every other point.")
.plan[["nativecmp_signalingRole_scatter_pair_twin"]] <- list(
  id = "nativecmp_signalingRole_scatter_pair_twin",
  axis = "contrast",
  by = "tool",
  fn = "netAnalysis_signalingRole_scatter",
  device = "png",
  w = quote(2600),
  h = quote(1700),
  expr = quote({
 gg <- Filter(Negate(is.null), role)
 if (!length(gg)) stop("neither object returned a role scatter")
 lim <- range(unlist(lapply(gg, function(g) c(g$data$x, g$data$y))), na.rm = TRUE)
 .padr <- diff(lim) * 0.08
 lim <- c(lim[1] - .padr, lim[2] + .padr)
 smax <- max(unlist(lapply(gg, function(g) g$data$Count)), na.rm = TRUE)
 for (i in seq_along(gg)) gg[[i]] <- gg[[i]] + ggplot2::xlim(lim) + ggplot2::ylim(lim) +
 ggplot2::scale_size_continuous(limits = c(0, smax)) +
 ggplot2::ggtitle(names(role)[i])
 patchwork::wrap_plots(plots = gg)
 }),
  legend = "One sender-against-receiver scatter per arm, drawn on shared axes and a shared point scale so the two are comparable by eye, a comparison this panel adds beyond what either single-arm scatter carries alone. Each point is a population: outgoing strength horizontally, incoming vertically, and point size is the number of inferred links. Nothing is tested. Each point's label is placed, and its leader line drawn or withheld, by an automatic label-repel step, and each point's colour comes from a shared colour map when the cohort provides one, or a default palette otherwise; neither the leader-line threshold nor a colour chosen to keep two nearby points visually apart is reachable through this call's own arguments, so two points that sit close together can still carry unled, centred labels, and two points can still land in a similar hue. A population that appears in either arm's own single-panel version of this scatter can still be missing from both sides here; the single-arm panel beside each side of this pair carries the complete roster to check against.")
.plan[["native_heatmap_count"]] <- list(
  id = "native_heatmap_count",
  axis = "group",
  by = "tool",
  fn = "netVisual_heatmap",
  device = "ndev",
  at_most = 1,
  expr = quote({
 ComplexHeatmap::draw(
 netVisual_heatmap(cc, measure = "count", color.heatmap = "Blues", color.use = .gcol,
 title.name = .ttl("interactions")),
 column_title = "Targets (Receiver)", column_title_side = "bottom")
 }),
  legend = "Senders down the rows, receivers across the columns; colour is the number of inferred interactions for that ordered pair. The colour scale is fitted to this unit's own maximum and is not shared with any other unit's copy of this heatmap, so the same shade on two plates is not the same count; the bars beside each plate carry the actual totals to check against. The reading is directional: the cell at row i, column j is i signalling to j, and is not the cell opposite it.")
.plan[["nativecmp_diff_heatmap_count"]] <- list(
  id = "nativecmp_diff_heatmap_count",
  axis = "contrast",
  by = "tool",
  fn = "netVisual_heatmap",
  device = "ndev",
  at_most = 1,
  w = quote(2400),
  h = quote(1800),
  expr = quote(ComplexHeatmap::draw( netVisual_heatmap(m, measure = "count", color.use = .ccol, title.name = .diffttl("Differential number of interactions")))),
  legend = "Which population pairs differ in the number of inferred interactions between the two arms, as a matrix: senders down the rows, receivers across the columns. Red is higher in the second arm, blue is higher in the reference. A pale cell means the two arms agree there, which is not the same as neither arm having interactions. Restricted to the populations both arms carry; a population present in only one arm has no difference to plot and is not on either axis. The colour key's own printed ticks follow only the larger-magnitude sign; a cell of the smaller sign is coloured below the first printed tick, off the labelled scale, with red still meaning higher in the second arm and blue still meaning higher in the reference.")
.plan[["nativecmp_diff_heatmap_weight"]] <- list(
  id = "nativecmp_diff_heatmap_weight",
  axis = "contrast",
  by = "tool",
  fn = "netVisual_heatmap",
  device = "ndev",
  at_most = 1,
  w = quote(2400),
  h = quote(1800),
  expr = quote(ComplexHeatmap::draw( netVisual_heatmap(m, measure = "weight", color.use = .ccol, title.name = .diffttl("Differential interaction strength")))),
  legend = "The same differential matrix on interaction strength rather than count. Red is higher in the second arm, blue in the reference. Strength and count can move in opposite directions for one pair: it can gain interactions while each of them weakens, which is why the two panels are drawn together. Restricted to the same shared populations as its count sibling, for the same reason. The colour key's own printed ticks follow only the larger-magnitude sign; a cell of the smaller sign is coloured below the first printed tick, off the labelled scale, with red still meaning higher in the second arm and blue still meaning higher in the reference.")
.plan[["nativecmp_interaction"]] <- list(
  id = "nativecmp_interaction",
  axis = "interaction",
  by = "plugin",
  fn = "",
  device = "ndev",
  at_most = 6,
  file = quote(paste0("interaction_", ms, "__", safe)),
  expr = quote({
 mx <- max(abs(M), na.rm = TRUE)
 ttl <- paste0("Does the ", fac, " response depend on ",
 as.character(rows$stratum_factor[1]), "?   (", ms_lbl, ")")
 sub <- paste0("(", as.character(rows$against[1]), " - ",
 as.character(rows$reference[1]), ") within ", st[1],
 "   minus   (", as.character(rows$against[2]), " - ",
 as.character(rows$reference[2]), ") within ", st[2], " (control)",
 "\nRED: ", fac, " response larger in ", st[1],
 "     BLUE: larger in ", st[2])
 ComplexHeatmap::draw(ComplexHeatmap::Heatmap(
 M, name = paste0("interaction\n(", ms_short, ")\n+ = larger in\n", st[1]),
 col = circlize::colorRamp2(c(-mx, 0, mx), c("#2166ac", "white", "#b2182b")),
 border = TRUE,
 rect_gp = grid::gpar(col = "grey88", lwd = 0.4),
 cluster_rows = FALSE, cluster_columns = FALSE,
 row_title = "Sources (Sender)", column_title_side = "top",
 row_title_gp = grid::gpar(fontsize = 10),
 row_names_side = "left",
 row_names_gp = grid::gpar(fontsize = 8),
 column_names_gp = grid::gpar(fontsize = 8),
 column_title = paste0(ttl, "\n", sub),
 column_title_gp = grid::gpar(fontsize = 9)),
 column_title = "Targets (Receiver)", column_title_side = "bottom",
 column_title_gp = grid::gpar(fontsize = 10))
 }),
  legend = "Does the {fac} response depend on {as.character(rows$stratum_factor[1])}? Per ordered population pair, for {ms_lbl}: the {eff_lbl} within {st[1]} minus the same response within {st[2]}, which is the control. Red means the {fac} response is larger in {st[1]}; blue means larger in {st[2]}; white means the same response in both, which is no interaction and not an absence of signalling. Rows are senders, columns are receivers. Drawn on the {nrow(M)} populations present in every arm, which is fewer than the two-arm panels carry. For two factors crossed this way the interaction is symmetric: naming the other factor the response gives the identical matrix, so this panel and its counterpart under the other framing carry the same values under two equivalent questions. Values are the merged object's own matrices; no test applies to a difference of two differences.{ms_unit}{ms_note}")
.plan[["native_signalingRole_scatter"]] <- list(
  id = "native_signalingRole_scatter",
  axis = "group",
  by = "tool",
  fn = "netAnalysis_signalingRole_scatter",
  device = "png",
  expr = quote({
 gg <- netAnalysis_signalingRole_scatter(cc, color.use = .gcol, label.size = 2.0)
 .xr <- range(gg$data$x, na.rm = TRUE)
 gg <- gg + ggplot2::xlim(.xr[1] - diff(.xr) * 0.04, .xr[2] + diff(.xr) * 0.14)
 gg + ggplot2::labs(caption = if (nzchar(.fctx$stamp)) .fctx$stamp else NULL)
 }),
  legend = "Each population is placed by how much inferred signalling it sends (horizontal) against how much it receives (vertical), for this unit alone. Both axes are scaled to this unit's own data and are not matched to any other unit's copy of this plot, so a point's position cannot be read against the same point on another unit's version without checking both axes' ranges. Distance from the diagonal is how one-sided a population is. Point size is the number of inferred links. Nothing here is a comparison and nothing is tested. Text labels are placed by an automatic label-repel step that can still set a label directly on its own point when several populations sit close together; label size has already been lowered once for a different crowding defect on this same panel, and a further reduction was found not to move a label off the point it sits on, so this is the automatic placement rather than an omission reachable through this call's own arguments.")
.plan[["native_circle_weight"]] <- list(
  id = "native_circle_weight",
  axis = "unit",
  by = "tool",
  fn = "netVisual_circle",
  device = "png",
  expr = quote({
 netVisual_circle(cc@net$weight, vertex.weight = as.numeric(table(cc@idents)),
 weight.scale = TRUE, label.edge = FALSE, color.use = .gcol,
 vertex.label.cex = 0.5, title.name = "interaction strength")
 graphics::legend("bottomleft", bty = "n", cex = 0.65,
 legend = c("edge colour = the sending population (matches its node)",
 "edge width = summed communication probability sent"))
 .stampf()
 }),
  legend = "Every one of the {ngrp} populations is a node on a ring and every inferred interaction an edge. Node size is the number of cells in that population; edge width is the summed communication probability inferred from the sender to the receiver, not a count of interactions, and edge colour is the sender. A population with no inferred communication in either direction can render as an unfilled outline rather than a solid circle, which is the drawing's own way of showing zero strength and not a missing population; the {ngrp} here is this unit's own roster and is not necessarily the set another unit's copy of this figure carries. The ring is a layout and nothing more: a node position on it carries no meaning, and neither does the distance between two nodes. Inferred from expression, not measured.")
.plan[["native_signalingRole_heatmap_out"]] <- list(
  id = "native_signalingRole_heatmap_out",
  axis = "group",
  by = "tool",
  fn = "netAnalysis_signalingRole_heatmap",
  device = "png",
  at_most = 1,
  expr = quote(netAnalysis_signalingRole_heatmap(cc, pattern = "outgoing", width = 10, height = 12)),
  legend = "Which signalling programmes this unit sends, and from which populations. Rows are programmes, columns are populations. Colour is relative strength rescaled within each row, so it shows where a programme acts and not how strong one programme is against another. The bars above and beside are the column and row totals. The colour key's floor is this plate's own minimum value rather than a fixed zero, so it is not shared across arms: a white cell can mean a true zero on one arm's plate and a small nonzero value on another's. One unit, no comparison.")
.plan[["nativecmp_signalingRole_heatmap"]] <- list(
  id = "nativecmp_signalingRole_heatmap",
  axis = "contrast",
  by = "tool",
  fn = "netAnalysis_signalingRole_heatmap",
  device = "ndev",
  at_most = 1,
  w = quote(1800),
  h = quote(1700),
  items = quote(c("outgoing", "incoming")),
  file = quote(paste0("signalingRole_heatmap_", pat)),
  expr = quote({
 allp <- union(object.list[[1]]@netP$pathways, object.list[[2]]@netP$pathways)
 .cen <- function(o, how) {
 cs <- o@netP$centr
 m <- sapply(names(cs), function(k) {
 v <- if (pat == "outgoing") cs[[k]]$outdeg else cs[[k]]$indeg
 if (is.null(v) || !length(v)) rep(0, nlevels(o@idents)) else as.numeric(v)
 })
 if (!length(m)) return(0)
 m <- matrix(unlist(m), ncol = length(cs))
 if (how == "top") max(colSums(m), na.rm = TRUE) else max(rowSums(m), na.rm = TRUE)
 }
 yt <- max(sapply(object.list, .cen, how = "top"), na.rm = TRUE)
 yr <- max(sapply(object.list, .cen, how = "right"), na.rm = TRUE)
 hs <- lapply(seq_along(object.list), function(i)
 netAnalysis_signalingRole_heatmap(object.list[[i]], pattern = pat, signaling = allp,
 title = names(object.list)[i], width = 6, height = 14, font.size = 7,
 ylim.top = c(0, yt), ylim.right = c(0, yr)))
 ComplexHeatmap::draw(hs[[1]] + hs[[2]], ht_gap = grid::unit(0.5, "cm"))
 }),
  legend = "Pathways down the rows, populations across the columns, for {pat} signalling: one heatmap per arm, side by side, on one shared colour scale and shared marginal axes so the two can be compared. Colour is centrality, not communication probability, and it is rescaled within each row, so a pathway drawn near-maximum in most of its cells is near-maximum against its own row, a different quantity from the right-margin total bar, so a large-looking row and a small right-margin bar are not a contradiction. A pathway present in one arm and absent in the other is drawn as zeros in the arm that lacks it. A row whose right-hand marginal bar renders as a single solid block rather than the usual thin proportional bar, or extends in the opposite direction from its neighbours, is the underlying centrality annotation for that pathway rather than a choice made here: the marginal axes' range is shared across both arms, but how any one bar within it is drawn is not. The panel titles printed above each heatmap are the same automatic annotation and can sit a small coloured block over an arm name's own last letter, which the shared marginal axes do not reach. The colour key's own floor is not one of the ranges shared across the pair, only the top and right marginal axes are, so the same green can start at zero in one arm's key and just above zero in the other's, a scale-floor difference drawn independently per heatmap.")
.plan[["nativecmp_interaction_lr"]] <- list(
  id = "nativecmp_interaction_lr",
  axis = "interaction",
  by = "plugin",
  fn = "interaction_lr",
  device = "png",
  at_most = 2,
  w = quote(2200),
  file = quote(paste0("interaction_lr__", safe)),
  expr = quote({
 dd <- lr$d
 dd$label <- factor(dd$label, levels = rev(dd$label))
 ggplot2::ggplot(dd, ggplot2::aes(x = label, y = ix, fill = ix > 0)) +
 ggplot2::geom_col(show.legend = FALSE) +
 ggplot2::geom_hline(yintercept = 0, linewidth = 0.3) +
 ggplot2::coord_flip() +
 ggplot2::scale_fill_manual(values = c(`TRUE` = "#b2182b", `FALSE` = "#2166ac")) +
 ggplot2::labs(x = NULL,
 y = paste0(eff_lbl, " within ", st[1], " minus the same within ", st[2],
 "\n(percentage points of each arm's total communication ",
 "probability)"),
 title = paste0("Which ligand-receptor pairs respond to ", fac,
 " differently between ", st[1], " and ", st[2], "?"),
 subtitle = paste0("RED: the ", fac, " response is larger in ", st[1],
 "    BLUE: larger in ", st[2],
 "\n", nrow(dd), " of ", lr$n_all,
 " pairs present in all four arms, of ", lr$n_any,
 " seen in any")) +
 ggplot2::theme_classic() +
 ggplot2::theme(axis.text.y = ggplot2::element_text(size = 7))
 }),
  legend = "Which ligand-receptor pairs respond to {fac} differently between {st[1]} and {st[2]}? Each bar is one pair: the {eff_lbl} within {st[1]} minus the same response within {st[2]}, which is the control. Red means the response is larger in {st[1]}; blue means larger in {st[2]}. In brackets after each pair is the sender and receiver carrying most of it, so the pair is read in a cell type rather than on its own. Values are percentage points: each arm's pairs are expressed as a share of that arm's own total before any difference is taken, because a communication probability is normalised within its own object. Drawn on the {nrow(lr$d)} largest of {lr$n_all} pairs present in all four arms, out of {lr$n_any} seen in any of them; a pair absent from one arm has no difference of differences and is not shown. No test applies to a difference of two differences and none is claimed.")
.plan[["nativecmp_interaction_lr_scatter"]] <- list(
  id = "nativecmp_interaction_lr_scatter",
  axis = "interaction",
  by = "plugin",
  fn = "interaction_lr",
  device = "png",
  at_most = 2,
  w = quote(2400),
  file = quote(paste0("interaction_lr_scatter__", safe)),
  expr = quote({
 dd <- lr$d
 .r <- range(c(dd$resp1, dd$resp2), na.rm = TRUE)
 .pad <- max(diff(.r) * 0.10, 1e-9)
 .lim <- c(.r[1] - .pad, .r[2] + .pad)
 .lab <- dd[dd$flip, , drop = FALSE]
 .lab <- .lab[order(-abs(.lab$ix)), , drop = FALSE]
 .lab <- utils::head(.lab, 10)
 .repel <- requireNamespace("ggrepel", quietly = TRUE)
 .lab_layer <- if (.repel)
 ggrepel::geom_text_repel(data = .lab, ggplot2::aes(label = pair), size = 2.6,
 min.segment.length = 0, segment.size = 0.25,
 segment.colour = "grey55", box.padding = 0.45,
 max.overlaps = Inf, seed = 1L)
 else
 ggplot2::geom_text(data = .lab, ggplot2::aes(label = pair), size = 2.6, hjust = -0.1)
 ggplot2::ggplot(dd, ggplot2::aes(x = resp2, y = resp1)) +
 ggplot2::annotate("rect", xmin = -Inf, xmax = 0, ymin = 0, ymax = Inf,
 fill = "#b2182b", alpha = 0.06) +
 ggplot2::annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = 0,
 fill = "#2166ac", alpha = 0.06) +
 ggplot2::geom_hline(yintercept = 0, linewidth = 0.3, colour = "grey40") +
 ggplot2::geom_vline(xintercept = 0, linewidth = 0.3, colour = "grey40") +
 ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed",
 linewidth = 0.4, colour = "grey30") +
 ggplot2::geom_point(ggplot2::aes(colour = flip), size = 2.4, alpha = 0.9) +
 .lab_layer +
 ggplot2::scale_colour_manual(values = c(`TRUE` = "#b2182b", `FALSE` = "grey45"),
 labels = c(`TRUE` = "direction overturns",
 `FALSE` = "same direction in both"),
 name = NULL) +
 ggplot2::coord_equal(xlim = .lim, ylim = .lim) +
 ggplot2::labs(
 x = paste0(eff_lbl, " within ", st[2], " (the control)"),
 y = paste0(eff_lbl, " within ", st[1]),
 title = paste0("Does any ligand-receptor pair respond to ", fac,
 " in OPPOSITE directions between ", st[1], " and ", st[2], "?"),
 subtitle = paste0("Axes: percentage points of each arm's own total.\n",
 "Dashed line = no interaction. Shaded quadrants = direction ",
 "overturns (", lr$n_flip, " of ", lr$n_all, " pairs; ",
 nrow(.lab), " named).")) +
 ggplot2::theme_classic() +
 ggplot2::theme(legend.position = "top")
 }),
  legend = "Each point is one ligand-receptor pair, placed by its {eff_lbl} within {st[1]} (vertical) against the same response within {st[2]}, which is the control (horizontal). Both axes are percentage points of each arm's total communication probability, so a value is a pair's share of its own arm before any difference is taken. The dashed diagonal is no interaction, an identical response in both strata, so a point's distance from it is the interaction. The shaded quadrants mark the overturns: a pair there responds to {fac} in one direction within {st[1]} and in the opposite direction within {st[2]}, which the bar panel beside this one cannot show, because a difference of +1 against -1 and one of +8 against +5 are both simply a gap. {lr$n_flip} of {lr$n_all} pairs present in all four arms overturn. Overturning pairs are labelled, the largest reversals first, and the count of both is on the plate; the rest are not labelled, to keep the panel readable. No test applies to a difference of two differences and none is claimed.")
.plan[["nativecmp_bubble_comparison"]] <- list(
  id = "nativecmp_bubble_comparison",
  axis = "contrast",
  by = "tool",
  fn = "netVisual_bubble",
  device = "png",
  w = quote(.bw),
  h = quote(5200),
  expr = quote(netVisual_bubble(m, comparison = c(1, 2), angle.x = 90, remove.isolate = TRUE, font.size = 6, font.size.title = 9, title.name = paste("every enriched pair -", name_a, "against", name_b))),
  legend = "Every enriched ligand-receptor pair, {name_a} against {name_b}. Rows are pairs, columns are sender to receiver within each arm; colour is the communication probability and dot size is the permutation p-value, so size is confidence and not strength. Pairs with nothing to show in either arm are dropped, so an absent row was not tested and found empty. The dot colour key's own minimum and maximum labelling is fixed by the underlying routine and is not an argument this call exposes to change, and the wrapped column labels are sized by a canvas-width formula of twenty pixels of device per column at the six-point font already used here, enough to clear a collision a narrower canvas once produced; the column count is set by the page design rather than by this panel, so enlarging the font again would shrink that same margin back toward the overlap it was written to remove.")
.plan[["native_patterns"]] <- list(
  id = "native_patterns",
  axis = "group",
  by = "tool",
  fn = "identifyCommunicationPatterns",
  device = "ndev",
  at_most = 1,
  h = quote(2200),
  items = quote(c("outgoing", "incoming")),
  file = quote(paste0("patterns_", pat)),
  expr = quote({
 ccp <- identifyCommunicationPatterns(cc, pattern = pat, k = 3, width = 5, height = 16)
 grid::grid.text(paste0("communication patterns - ", pat),
 x = 0.5, y = 0.97, gp = grid::gpar(fontface = "bold", fontsize = 13))
 grid::grid.text("columns, left to right, both heatmaps: P1   P2   P3",
 x = 0.5, y = 0.945, gp = grid::gpar(fontsize = 9))
 assign(paste0("ccp_", pat), ccp, envir = globalenv())
 NULL
 }),
  legend = "The {pat} communication patterns, from a non-negative factorisation. Two heatmaps: populations against patterns, and patterns against pathways. Colour is loading, not communication probability. The number of patterns was fixed at three and not selected; a different k gives a different decomposition, so this is one grouping of the signal rather than the grouping. The P1/P2/P3 header above both heatmaps names the same left-to-right column order in each; neither heatmap prints that header on its own axis. The pair of heatmaps is laid by the underlying routine into roughly the bottom two-thirds of whatever device this call opens, a placement decided by its own internal grid layout and not by an argument this call exposes to move; the device height here is sized for the longer of the two pattern lists this cohort can produce, so a unit whose list is shorter leaves the blank margin above the panels that this costs, and that margin is where the pattern title and column header above are already printed.")
.plan[["nativecmp_rankSimilarity_functional"]] <- list(
  id = "nativecmp_rankSimilarity_functional",
  axis = "contrast",
  by = "tool",
  fn = "rankSimilarity",
  device = "png",
  w = quote(1600),
  h = quote(2000),
  expr = quote({
 gg <- rankSimilarity(m, type = "functional")
 gg + ggplot2::theme(axis.text.x = ggplot2::element_text(), axis.ticks.x = ggplot2::element_line()) +
 ggplot2::labs(title = paste0("Functional rank similarity - ", name_a, " against ", name_b))
 }),
  legend = "The {length(union(a@netP$pathways, b@netP$pathways))} pathways either arm inferred, ranked by how far they moved in the joint functional embedding: the largest values are the pathways whose participating populations differ most between the arms. It ranks a change in role, not a change in amount, so a pathway can carry the same flow in both arms and still rank highly here.")
.plan[["nativecmp_aggregate_circle"]] <- list(
  id = "nativecmp_aggregate_circle",
  axis = "contrast",
  by = "tool",
  fn = "netVisual_aggregate",
  device = "ndev",
  at_most = 1,
  w = quote(2800),
  h = quote(1500),
  file = quote(paste0("aggregate_circle__", safe)),
  expr = quote({
 graphics::par(mfrow = c(1, 2), xpd = TRUE)
 for (i in seq_along(object.list)) {
 netVisual_aggregate(object.list[[i]], signaling = pw, layout = "circle",
 edge.weight.max = wmax,
 signaling.name = paste(pw, names(object.list)[i]))
 graphics::legend("bottomleft", bty = "n", cex = 0.65,
 legend = c("edge colour = the sending population (matches its node)",
 "edge width = communication probability for this pathway"))
 }
 }),
  legend = "The {pw} pathway, one of the first {.entry$at_most} of the {length(paths)} pathways both arms carry, in the reference arm's own order, drawn once per arm, side by side, on a shared maximum edge weight so the two rings are comparable. Edge colour is the sending population, matching its node, and edge width is the inferred communication probability for this pathway; position on the ring carries no meaning. A missing edge in one arm is an inference that arm did not make.")
.plan[["nativecmp_barplot_count"]] <- list(
  id = "nativecmp_barplot_count",
  axis = "contrast",
  by = "tool",
  fn = "netVisual_barplot",
  device = "png",
  at_most = 1,
  w = quote(2200),
  h = quote(1700),
  expr = quote({
 gg <- netVisual_barplot(m, comparison = c(1, 2), measure = "count",
 sources.use = seq_along(group_new), x.lab.rot = TRUE)
 .miss <- c(
 if (length(absent)) paste0("no counterpart in the other arm: ", paste(absent, collapse = ", ")) else character(0),
 if (length(.iso_count)) paste0("present in both, no measured difference: ", paste(.iso_count, collapse = ", ")) else character(0))
 gg + ggplot2::labs(
 y = paste0("Difference in number of interactions  (", name_b, " minus ", name_a, ")"),
 title = paste0("Differential number of interactions by population  -  ",
 name_b, " minus ", name_a),
 subtitle = if (length(.miss)) paste(.miss, collapse = ";  ") else NULL) +
 ggplot2::theme(plot.margin = ggplot2::margin(l = 50, r = 15, t = 10, b = 10))
 }),
  legend = "Which populations account for the change in the number of inferred interactions between the two arms: one bar per population, not one bar per arm, its height the population's outgoing edges in {name_b} minus the same in {name_a}, the reference. Positive means more interactions in {name_b}; negative means more in {name_a}. A single fit per arm sits behind each side of the subtraction, so this is arithmetic, not a tested difference. A population missing from the bars is named in the subtitle, either with no counterpart in the other arm or, if present in both, unchanged between them on this measure, the same disclosure the differential ring carries for the identical reason.")
.plan[["nativecmp_compareInteractions"]] <- list(
  id = "nativecmp_compareInteractions",
  axis = "interaction",
  by = "tool",
  fn = "compareInteractions",
  device = "png",
  at_most = 2,
  w = quote(max(1500, 340 * length(objs))),
  h = quote(1300),
  items = quote(c("count", "weight")),
  file = quote(paste0("compareInteractions_", ms)),
  expr = quote(g),
  legend = "Total {if (ms == \"count\") \"number of inferred interactions\" else \"interaction strength\"} in each arm the design crosses, one bar per arm, from one fit on that arm's pooled cells. Open points are the individual samples inside each arm, each its own separate fit: the bar is not their sum or their mean, and on this cohort an arm's fit finds fewer interactions than its samples do separately. Nothing here is tested; these are totals with no interval.")
.plan[["nativecmp_compareInteractions_per1k"]] <- list(
  id = "nativecmp_compareInteractions_per1k",
  axis = "interaction",
  by = "plugin",
  fn = "",
  device = "png",
  at_most = 2,
  w = quote(max(1500, 340 * length(objs))),
  h = quote(1300),
  items = quote(c("count", "weight")),
  file = quote(paste0("compareInteractions_per1k_", ms)),
  expr = quote(gg),
  legend = "The open points here mark individual replicate samples underlying each arm's bar; this bar-plus-dots panel draws no legend for them on the image itself, so this caption, not the plate, is where a reader finds what they are and how each is computed. The same totals divided by the cells each fit used, per 1,000 cells. A second scale, not a correction: the quantity does not rise linearly with cell number, so dividing puts the arithmetic on the page rather than removing the dependence. {if (.decomposed) paste0( \"Each open point is one animal's share of this arm's own fit, \", \"credited by that animal's share of the arm's cells in the two \", \"populations of each pair, half for sending, half for receiving. \", \"That split is exact, so the bar is the cell-weighted mean of its \", \"own points and a point may fall on either side of it. It is a \", \"derived attribution rather than a quantity the method reports \", \"directly: the fit uses the arm's pooled cells and says nothing \", \"about which animal carried which edge. Each animal's independent \", \"fit is the raw panel beside this one.\") else paste0( \"Each point is one sample's own fit divided by its own cells. A \", \"pooled arm and a single sample are not comparable on this scale, \", \"because a smaller fit finds proportionally more; the points are \", \"comparable against each other and not against the bar.\")}")
.plan[["nativecmp_chord_cell"]] <- list(
  id = "nativecmp_chord_cell",
  axis = "contrast",
  by = "tool",
  fn = "netVisual_chord_cell",
  device = "ndev",
  at_most = 1,
  w = quote(1800),
  h = quote(1800),
  file = quote(paste0("chord_cell__", safe, "__", gsub("[^A-Za-z0-9]+", "_", names(object.list)[i]))),
  expr = quote(netVisual_chord_cell(object.list[[i]], signaling = pw, lab.cex = 0.45, small.gap = 1, big.gap = 8, title.name = paste(pw, names(object.list)[i]))),
  legend = "The {pw} pathway as a chord diagram, one per arm, one of the first {.entry$at_most} of the {length(paths)} pathways both arms carry, in the reference arm's own order: each ribbon runs from a sending population to a receiving one and ribbon width is the inferred communication probability. This is population-level, where the gene chord is pair-level. The ordering around the circle is a layout and carries no meaning. A shorter canvas was tried to close up this panel's blank margin and it failed for every pathway on both arms, because the underlying layout refuses to draw its own sector track below a minimum size that depends on how many cell-state sectors and how long their labels are for a given unit, a size not computable here without rendering that layout itself and not safe to guess at again on a live dataset; so the canvas stays at the size already proven to draw everywhere and the blank margin is the cost of that safety.")
.plan[["nativecmp_signalingChanges_scatter"]] <- list(
  id = "nativecmp_signalingChanges_scatter",
  axis = "contrast",
  by = "tool",
  fn = "netAnalysis_signalingChanges_scatter",
  device = "png",
  at_most = 1,
  expr = quote(netAnalysis_signalingChanges_scatter(m, idents.use = pop, comparison = c(1, 2))),
  legend = "The change in each population signalling role between the two arms: outgoing strength against incoming strength, one point per population, arrows from the first arm to the second.")

# THE INTERPRETER. `.draw(id)` draws one entry of the plan where a hand-written site stood;
# `.draw_all(axis)` draws every entry of an axis, `.item` bound over an entry's items. Every
# expression the entry carries is evaluated in the frame `.draw` is called from - the method's
# own locals are what the site saw, and they are what the plan's entry sees.
.items <- function(x) {
  x <- as.character(x)
  x[!is.na(x) & nzchar(x)]
}

# A LEGEND IS A TEMPLATE WHOSE {...} ARE R EXPRESSIONS, evaluated where the draw is called. A
# placeholder that fails to evaluate is reported and rendered as "?", never as a silent blank:
# the panel is still drawn, and the log says which sentence lost which fact.
.fill <- function(template, env) {
  if (is.null(template) || !nzchar(template)) return("")
  m <- gregexpr("\\{[^{}]+\\}", template)
  holes <- regmatches(template, m)[[1]]
  if (!length(holes)) return(template)
  vals <- vapply(holes, function(h) {
    ex <- substr(h, 2L, nchar(h) - 1L)
    tryCatch(paste(as.character(eval(parse(text = ex), env)), collapse = ", "),
             error = function(e) {
               cat("legend placeholder failed: {", ex, "} - ", conditionMessage(e), "\n", sep = "")
               "?"
             })
  }, character(1))
  regmatches(template, m) <- list(vals)
  template
}

.draw <- function(id, item = NULL, env = parent.frame()) {
  e <- .plan[[id]]
  # NOT ON THE PLAN IS NOT AN ERROR (harness ADR-0024): the layout trims the plan in the
  # plugin's file, and a draw site that still names a dropped entry is skipped and says so.
  if (is.null(e)) {
    cat("not on the plan: ", id, " - skipped; the layout holds the plan\n", sep = "")
    return(invisible(NULL))
  }
  # A MARGINAL POOL DRAWS NOTHING: fitted for the marginal contrasts, and under the layout the
  # group axis is the design's arms.
  if (identical(.fctx$axis, "margin")) {
    cat("not drawn: ", id, " - this unit is a marginal pool, fitted for the marginal ",
        "contrasts; a pool draws no figure of its own\n", sep = "")
    return(invisible(NULL))
  }
  # AN ENTRY FOR ONE KIND OF UNIT: `sample` or `group` on the entry, the unit's own axis from the
  # host's figure context; a mismatch is skipped, not drawn.
  if (!is.null(e$axis) && e$axis %in% c("sample", "group") && isTRUE(nzchar(.fctx$axis))
      && !identical(e$axis, .fctx$axis)) {
    cat("not for this unit's axis: ", id, " is drawn per ", e$axis, "; this unit is a ",
        .fctx$axis, "\n", sep = "")
    return(invisible(NULL))
  }
  if (!is.null(item)) assign(".item", item, envir = env)
  # THE ENTRY, VISIBLE TO ITS OWN LEGEND: `{.entry$at_most}` names the ceiling from the plan,
  # once, where a legend that retyped it said 8 while the declaration said 6.
  assign(".entry", e, envir = env)
  if (!is.null(e$when) && !isTRUE(eval(e$when, env))) return(invisible(NULL))
  # THE FILE STEM: the entry's own expression, or the id without this script's prefix - the
  # prefix is put back by the device path, as it was for every hand-written site.
  stem <- if (!is.null(e$file)) as.character(eval(e$file, env))
          else if (nzchar(.figcfg$prefix) && startsWith(id, .figcfg$prefix))
            substring(id, nchar(.figcfg$prefix) + 1L) else id
  w <- if (is.null(e$w)) .figcfg$w else eval(e$w, env)
  h <- if (is.null(e$h)) .figcfg$h else eval(e$h, env)
  res <- if (is.null(e$res)) .figcfg$res else eval(e$res, env)
  # THE CALL IS A PROMISE: `.draw_one` forces it inside the device, exactly as it forced the
  # expression a hand-written site passed it.
  .draw_one(stem, eval(e$expr, env), identical(e$device, "ndev"), w, h, res,
            legend = .fill(e$legend, env), by = e$by)
}

.draw_all <- function(axis, env = parent.frame()) {
  for (id in names(.plan)) {
    e <- .plan[[id]]
    # `unit` reaches the entries declared for a sample or a group too; `.draw` keeps the ones
    # for this unit's own axis.
    if (!identical(e$axis, axis)
        && !(identical(axis, "unit") && e$axis %in% c("sample", "group"))) next
    if (is.null(e$items)) {
      .draw(id, NULL, env)
    } else {
      for (.it in .items(eval(e$items, env))) .draw(id, .it, env)
    }
  }
  invisible(NULL)
}
