# cellchat - the host-to-plugin drawing protocol, in R.
#
# GENERATED by `scprofile scaffold cellchat`. Do not edit it here; edit the template in
# scprofile/scaffold.py and regenerate, or the next scaffold silently reverts you. `sch dev
# convert placement` regenerates this file and refuses a plugin whose copy has drifted.
#
# HOW A PLUGIN USES IT. Prepend it to every embedded R script the plugin runs, so ONE definition
# serves all of them:
#
#     script = _R_DRAW + _R_BODY            # in the Python that launches Rscript
#
# and configure it once per script, after `figdir` is known:
#
#     .figures(prefix = "native_", what = "native plot", w = 1800, h = 1500,
#              context = ctx_file, visible = function(id) draw_figs || id %in% profile_plots)
#
# WHY THIS IS ONE FILE AND NOT A BLOCK IN EACH SCRIPT. It was three blocks in one plugin, and the
# copies drifted. One of them recorded the cost in its own comment: a script "was written with only
# `npng` and then called `ndev` for the interaction heatmaps - could not find function ndev halted
# the whole framing loop after the first framing's scatter plots, so one framing of two was drawn
# and neither heatmap was. The sibling script had both wrappers; this one had one." A generated
# definition cannot have that defect. Three hand-written ones cannot avoid it.
#
# WHAT IS DELIBERATELY NOT HERE: anything about the method. This file knows about ceilings,
# captions, colours, devices and a phase clock - the things the HOST and the plugin agree on. It
# names no plotting function and no biology.

.figcfg <- new.env(parent = emptyenv())
.figcfg$prefix <- ""
.figcfg$what <- "figure"
.figcfg$w <- 1800
.figcfg$h <- 1400
.figcfg$res <- 200
.figcfg$visible <- function(id) TRUE

# WHAT THE HOST COMPUTED AND THE PLUGIN APPLIES. The host writes one tab-separated file beside the
# run and every row of it is a term of this contract: the provenance stamp, the sentence that says
# what an absent population means, the colour map that keeps one population one colour across every
# panel of the whole report, and the ceilings.
.fctx <- list(stamp = "", absence = "", colours = character(0))
.ceil <- integer(0)

.plots <- new.env(); .plots$ok <- 0L; .plots$bad <- character(0)
.caps <- new.env(); .caps$rows <- list()
.ndrawn <- new.env(parent = emptyenv())

.figures <- function(prefix = "", what = "figure", w = 1800, h = 1400, res = 200,
                     context = "", visible = NULL) {
  .figcfg$prefix <- prefix
  .figcfg$what <- what
  .figcfg$w <- w
  .figcfg$h <- h
  .figcfg$res <- res
  if (!is.null(visible)) .figcfg$visible <- visible
  if (nzchar(context) && file.exists(context)) {
    fc <- tryCatch(utils::read.delim(context, header = FALSE, sep = "\t", quote = "",
                                     comment.char = "", stringsAsFactors = FALSE,
                                     col.names = c("k", "v")), error = function(e) NULL)
    if (!is.null(fc) && nrow(fc)) {
      .fctx$stamp <<- paste(fc$v[fc$k == "stamp"], collapse = "")
      .fctx$absence <<- paste(fc$v[fc$k == "absence"], collapse = "")
      cr <- fc[startsWith(fc$k, "colour:"), , drop = FALSE]
      if (nrow(cr)) .fctx$colours <<- stats::setNames(cr$v, sub("^colour:", "", cr$k))
      cl <- fc[startsWith(fc$k, "ceiling:"), , drop = FALSE]
      if (nrow(cl)) .ceil <<- stats::setNames(suppressWarnings(as.integer(cl$v)),
                                              sub("^ceiling:", "", cl$k))
    }
  }
  invisible(NULL)
}

# THE VECTOR A PLOTTING FUNCTION WANTS: IN THE OBJECT'S LEVEL ORDER, AND NAMED.
#
# Ordered, because a plotting function takes a colour vector POSITIONALLY against the object's
# factor levels and any other order colours the wrong populations. NAMED, because some upstream
# functions refuse an unnamed one outright while others accept it either way - so the vector
# satisfies the stricter of them. Dropping the names once cost 36 circle plots across 18 units in
# one run, and the per-unit tallies reported the failure while the run-level count said nothing.
#
# Returns NULL when the host gave no map or when any level is unmapped, because a partial vector is
# worse than none: the plotting function would recycle it silently.
.cols_for <- function(levs) {
  if (!length(.fctx$colours)) return(NULL)
  levs <- as.character(levs)
  if (!all(levs %in% names(.fctx$colours))) return(NULL)
  out <- .fctx$colours[levs]
  names(out) <- levs
  out
}

# A PHASE CLOCK, DEFINED AT THE TOP BECAUSE R DOES NOT HOIST. Twice the cost of a round has been
# diagnosed by assumption and been wrong: the inference was assumed dominant and was not, then the
# matrix write was, and it takes one to five seconds. Guessing where a run spends its time is what
# makes every round of development expensive, so the run measures itself.
#
# t0 IS ZERO, NOT "NOW". `proc.time()` elapsed is measured from the moment R STARTED, so anchoring
# the clock at zero makes the first mark cover everything before it - interpreter start-up and
# loading the wrapped tool and its dependencies. Anchored at "now" the first phase reported 0 while
# the cost it was supposed to name sat outside the clock entirely, and a line that says zero is
# worse than no line because it reads as a measurement.
.clock <- new.env(); .clock$t0 <- 0; .clock$marks <- list()
mark <- function(what) {
  now <- proc.time()[["elapsed"]]
  .clock$marks[[what]] <- now - .clock$t0
  .clock$t0 <- now
  invisible(NULL)
}

.legend <- function(fname, text, by) {
  if (!nzchar(text)) return(invisible(NULL))
  .caps$rows[[length(.caps$rows) + 1L]] <-
    # ONE LINE, ALWAYS. The file is tab-separated and written with quote = FALSE, so a caption
    # carrying a tab or a newline does not corrupt one row - it shifts every column after it, or
    # splits the row in two, and the reader then drops what it cannot parse WITHOUT SAYING SO.
    # Collapsing whitespace here matches what the reader does anyway and makes the written file
    # unable to express the broken shape.
    list(file = fname, caption = gsub("[[:space:]]+", " ", trimws(text)), drawn_by = by)
  invisible(NULL)
}

.write_captions <- function() {
  # CALLED ON EXIT AS WELL AS AT THE END. An abort in a later section left `captions.tsv`
  # unwritten, so panels drawn BEFORE the failure silently lost their legends and fell back to
  # their filenames - a degradation that renders as a normal page.
  if (!length(.caps$rows)) return(invisible(NULL))
  # ONCE PER SET OF ROWS. This is called explicitly at the end of a script AND by the finalizer
  # below, and writing the same file twice put a duplicate line in every run's log.
  if (identical(.caps$written, length(.caps$rows))) return(invisible(NULL))
  .caps$written <- length(.caps$rows)
  d <- do.call(rbind, lapply(.caps$rows, function(r) as.data.frame(r, stringsAsFactors = FALSE)))
  utils::write.table(d, file.path(figdir, "captions.tsv"),
                     sep = "\t", row.names = FALSE, quote = FALSE)
  cat("wrote", nrow(d), "figure legend(s)\n")
}

# WHEN THE SCRIPT ENDS, HOWEVER IT ENDS - AND `on.exit` IS NOT THAT. An abort in a later section
# left `captions.tsv` unwritten, so panels drawn BEFORE the failure silently lost their legends
# and fell back to their filenames, which renders as a perfectly normal page. The guard written
# against it was `on.exit(.write_captions(), add = TRUE)` at the top level of the script, and a
# top-level `on.exit` in `Rscript` NEVER RUNS - not on error and not on a clean exit. Measured
# both ways. A finalizer registered with `onexit = TRUE` runs in both cases, so the protection
# the comment described exists for the first time.
invisible(reg.finalizer(.caps, function(e) .write_captions(), onexit = TRUE))

# THE CEILING, ENFORCED BEFORE THE PLOT IS COMPUTED. R is lazy - `expr` is a promise until it is
# forced - so refusing here costs the call and nothing else. Longest prefix wins, as everywhere
# else a plugin states a rule and an exception together, and a family no ceiling covers is
# unbounded exactly as it was before this existed.
#
# WHY IT IS HERE AND NOT IN THE LOOPS. The bounds a plugin honoured were `head(paths, 6)` and
# `head(.ranked, 8)`, typed in by hand beside a declaration that said 12 and 8. The plan read the
# declaration, the run obeyed the literals, and they agreed only while somebody kept them in step.
# The number now exists once, in the declaration, and arrives here.
#
# A CEILING THE DRAWING CODE DOES NOT READ IS A COMMENT. Remove this guard and the plugin still
# declares its ceilings, still reports them, and draws without bound. That state was reached once
# and every build check reported the plugin finished; `sch dev convert placement` now asks.
.at_ceiling <- function(id) {
  if (!length(.ceil)) return(FALSE)
  k <- names(.ceil)[startsWith(id, names(.ceil))]
  if (!length(k)) return(FALSE)
  k <- k[which.max(nchar(k))]
  cap <- .ceil[[k]]
  if (is.na(cap)) return(FALSE)
  n <- if (is.null(.ndrawn[[k]])) 0L else .ndrawn[[k]]
  if (n >= cap) {
    cat("ceiling: ", id, " not drawn - ", k, " declares at most ", cap, " here\n", sep = "")
    return(TRUE)
  }
  .ndrawn[[k]] <- n + 1L
  FALSE
}

# THE ONE DEVICE PATH. `force_it` is the only thing the two public wrappers disagree about, and it
# is the difference between a function that RETURNS a plot object and one that DRAWS as a side
# effect - see `ndev` below.
#
# THE LEGEND SLOT IS THE PARAMETER WHOSE DEFAULT IS THE EMPTY STRING. That is how the maker finds
# it without being told a name, in R or in Python, so keep the default as it is.
.draw_one <- function(id, expr, force_it, w = .figcfg$w, h = .figcfg$h,
                      res = .figcfg$res, legend = "", by = "tool") {
  if (!isTRUE(.figcfg$visible(id))) return(invisible(NULL))
  full <- paste0(.figcfg$prefix, id)
  if (.at_ceiling(full)) return(invisible(NULL))
  path <- file.path(figdir, paste0(full, ".png"))
  .legend(basename(path), legend, by)
  ok <- tryCatch({
    grDevices::png(path, width = w, height = h, res = res)
    dn <- grDevices::dev.cur()
    # THE SAFETY NET NAMES ITS OWN DEVICE. An unqualified `dev.off()` here closes whatever is
    # current, which after the explicit close below is somebody else's device.
    on.exit(if (dn %in% grDevices::dev.list()) grDevices::dev.off(dn), add = TRUE)
    if (force_it) force(expr) else print(expr)
    # CLOSED BEFORE THE FILE IS ASKED ABOUT, and this is not tidiness. `on.exit` fires when the
    # FUNCTION returns, so with the close left to it the `file.exists` below runs while the
    # device is still open - and whether the file is there by then is a property of the platform:
    # the Linux png device creates it on open, the macOS one on close. Measured, on a wrapper
    # written exactly that way: every panel drawn correctly was counted as FAILED on macOS and as
    # written on the cluster, from one line of R.
    grDevices::dev.off(dn)
    TRUE
  }, error = function(e) {
    cat(.figcfg$what, id, "FAILED:", conditionMessage(e), "\n")
    FALSE
  })
  # THE FILE, NOT ONLY THE ABSENCE OF AN ERROR. A plotting call that returns quietly without
  # putting anything on the device leaves a path that does not exist, and counting that as drawn
  # is how a declared plot came to be promised and never produced.
  if (ok && file.exists(path)) {
    .plots$ok <- .plots$ok + 1L
    cat(.figcfg$what, id, "written\n")
  } else {
    .plots$bad <- c(.plots$bad, id)
    if (file.exists(path)) unlink(path)
  }
  invisible(NULL)
}

npng <- function(id, expr, w = .figcfg$w, h = .figcfg$h, res = .figcfg$res,
                 legend = "", by = "tool") {
  .draw_one(id, expr, FALSE, w, h, res, legend, by)
}

# Some functions DRAW rather than return - a base-graphics network, a grid object that must be
# drawn, a function whose value is NULL. `print` on those prints nothing or errors, so this second
# wrapper evaluates for the side effect instead.
ndev <- function(id, expr, w = .figcfg$w, h = .figcfg$h, res = .figcfg$res,
                 legend = "", by = "tool") {
  .draw_one(id, expr, TRUE, w, h, res, legend, by)
}
